[package]
name = "generate-report"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-compat = "0.2.6"
derive_typst_intoval = "0.8.0"
include_dir = { version = "0.7.4", features = ["glob"] }
rayon = "1.12.0"
rfd = "0.17.2"
slint = "1.16.1"
tokio = { version = "1.53.1", features = ["time"] }
typst = "0.15.1"
typst-as-lib = { version = "0.16.0", features = ["packages", "reqwest", "typst-kit-embed-fonts", "typst-kit-fonts"] }
typst-pdf = "0.15.1"

[build-dependencies]
slint-build = "1.17.1"

[profile.release]
codegen-units = 1
lto = true